### ISSUE TITLE
EINTR in scripts

### ISSUE THREAD

**Issue by titouanc** [UrLab/hal#1]
```
2015-02-26 10:14:08,321 - run - ERROR - Restart light_stairs
Traceback (most recent call last):
  File "/home/titou/HAL/scripts/run.py", line 30, in new_main
    main()
  File "light_stairs.py", line 45, in main
    for trig_name, trig_active in hal.events():
  File "/home/titou/HAL/halpy/halpy/hal.py", line 87, in events
    buf += events.recv(16)
error: [Errno 4] Interrupted system call
```
- http://legacy.python.org/dev/peps/pep-0475/

**Comment by titouanc** [comment]
Port the mainloop(s) to asyncio ?

**Comment by titouanc** [comment]
Ported to asyncio; no mo4r bugz
